---
- name: install member.lghs.be vhost
  import_role:
    name: reverse-proxy-unix
  vars:
    vhost: members.lghs.be
    socket: /var/run/php/php7.2-fpm.sock


- name: install php
  import_role:
    name: php

- name: install composer
  import_role:
    name: composer

- name: install dependencies
  command: composer install
  args:
    chdir: "{{ members_site_root }}"
  become: true
  become_user: www-data

- name: clone members repository
  git:
    repo: https://github.com/LgHS/sign-in.git
    version: c28797ee5ef31a856e9396a6d548221ecadf2c84
    dest: "{{ members_site_root }}"
  become: true
  become_user: www-data

- name: generate env file
  template:
    src: .env.j2
    dest: "{{ members_site_root }}/.env"
    owner: root
    group: www-data
    mode: 0640


- name: create members database user
  postgresql_user:
    name: "{{ members_db_username }}"
    password:  "{{ members_db_password }}"
    role_attr_flags: LOGIN
  become_user: postgres

- name: create members database
  postgresql_db:
    name: "{{ members_db_database }}"
    encoding: UTF-8
    owner: "{{ members_db_username }}"
  become_user: postgres

#
# FIXME add changed_when
# changed: [roger] => {"changed": true, "cmd": ["php", "artisan", "migrate"], "delta": "0:00:00.292067", "end": "2018-10-13 13:36:20.241857", "rc": 0, "start": "2018-10-13 13:36:19.949790", "stderr": "", "stderr_lines": [], "stdout": "Migration table created successfully.\nMigrating: 2014_10_12_000000_create_users_table\nMigrated:  2014_10_12_000000_create_users_table\nMigrating: 2014_10_12_100000_create_password_resets_table\nMigrated:  2014_10_12_100000_create_password_resets_table\nMigrating: 2016_06_01_000001_create_oauth_auth_codes_table\nMigrated:  2016_06_01_000001_create_oauth_auth_codes_table\nMigrating: 2016_06_01_000002_create_oauth_access_tokens_table\nMigrated:  2016_06_01_000002_create_oauth_access_tokens_table\nMigrating: 2016_06_01_000003_create_oauth_refresh_tokens_table\nMigrated:  2016_06_01_000003_create_oauth_refresh_tokens_table\nMigrating: 2016_06_01_000004_create_oauth_clients_table\nMigrated:  2016_06_01_000004_create_oauth_clients_table\nMigrating: 2016_06_01_000005_create_oauth_personal_access_clients_table\nMigrated:  2016_06_01_000005_create_oauth_personal_access_clients_table\nMigrating: 2016_07_06_151059_create_sessions_table\nMigrated:  2016_07_06_151059_create_sessions_table\nMigrating: 2016_12_13_020121_entrust_setup_tables\nMigrated:  2016_12_13_020121_entrust_setup_tables\nMigrating: 2017_02_17_205536_create_payment_types_table\nMigrated:  2017_02_17_205536_create_payment_types_table\nMigrating: 2017_02_17_224145_create_transaction_types_table\nMigrated:  2017_02_17_224145_create_transaction_types_table\nMigrating: 2017_02_18_110341_create_transactions_table\nMigrated:  2017_02_18_110341_create_transactions_table\nMigrating: 2017_04_01_235430_create_notifications_table\nMigrated:  2017_04_01_235430_create_notifications_table\nMigrating: 2017_04_12_151022_create_reminders_table\nMigrated:  2017_04_12_151022_create_reminders_table", "stdout_lines": ["Migration table created successfully.", "Migrating: 2014_10_12_000000_create_users_table", "Migrated:  2014_10_12_000000_create_users_table", "Migrating: 2014_10_12_100000_create_password_resets_table", "Migrated:  2014_10_12_100000_create_password_resets_table", "Migrating: 2016_06_01_000001_create_oauth_auth_codes_table", "Migrated:  2016_06_01_000001_create_oauth_auth_codes_table", "Migrating: 2016_06_01_000002_create_oauth_access_tokens_table", "Migrated:  2016_06_01_000002_create_oauth_access_tokens_table", "Migrating: 2016_06_01_000003_create_oauth_refresh_tokens_table", "Migrated:  2016_06_01_000003_create_oauth_refresh_tokens_table", "Migrating: 2016_06_01_000004_create_oauth_clients_table", "Migrated:  2016_06_01_000004_create_oauth_clients_table", "Migrating: 2016_06_01_000005_create_oauth_personal_access_clients_table", "Migrated:  2016_06_01_000005_create_oauth_personal_access_clients_table", "Migrating: 2016_07_06_151059_create_sessions_table", "Migrated:  2016_07_06_151059_create_sessions_table", "Migrating: 2016_12_13_020121_entrust_setup_tables", "Migrated:  2016_12_13_020121_entrust_setup_tables", "Migrating: 2017_02_17_205536_create_payment_types_table", "Migrated:  2017_02_17_205536_create_payment_types_table", "Migrating: 2017_02_17_224145_create_transaction_types_table", "Migrated:  2017_02_17_224145_create_transaction_types_table", "Migrating: 2017_02_18_110341_create_transactions_table", "Migrated:  2017_02_18_110341_create_transactions_table", "Migrating: 2017_04_01_235430_create_notifications_table", "Migrated:  2017_04_01_235430_create_notifications_table", "Migrating: 2017_04_12_151022_create_reminders_table", "Migrated:  2017_04_12_151022_create_reminders_table"]}
#
- name: migrate database
  command: "php artisan migrate"
  args:
    chdir: "{{ members_site_root }}"

- name: install passport
  command: "php artisan passport:install"
  args:
    chdir: "{{ members_site_root }}"
    creates: "{{ members_site_root }}/storage/oauth-private.key"

- name: secure passport key
  file:
    dest: "{{ members_site_root }}/storage/oauth-private.key"
    mode: 0640
    owner: root
    group: www-data

- name: warmup cache
  command: "php artisan {{ item }}"
  with_items:
    - config:cache
    - optimize
  args:
    chdir: "{{ members_site_root }}"
